### ISSUE TITLE
New release for 9.5?

### ISSUE THREAD

**Issue by devrimgunduz** [2ndquadrant-it/pgespresso#7]
Hi,

Can you please release a new version that supports 9.5? I can see that the patch is already in.

Thanks!

Regards, Devrim

**Comment by devrimgunduz** [comment]
Hi,

Any updates with this?

Regards, Devrim

**Comment by devrimgunduz** [comment]
Hi,

Ping.

**Comment by mnencia** [comment]
I'll do it in the weekend.
Il 20/Mag/2016 20:03, Devrim Gündüz <notifications@github.com> ha scritto:Hi,

Ping.

**Comment by mnencia** [comment]
I've just tagged the 1.1 release which supports 9.5.
